Update manifests
This fixes the following error when using v1.12 due to the
JuliaSyntaxHighlighting UUID change [0]:

```
ERROR: LoadError: cannot find name corresponding to UUID dc6e5ff7-fb65-4e79-a425-ec3bc9c03011 in a registry
```

[0]
https://github.com/JuliaLang/JuliaSyntaxHighlighting.jl/commit/eb8097c5f1dbfca80b5e6664af031ff1fe0904af